import { randomUUID } from 'node:crypto';
import { Queue } from 'bullmq';
import { z } from 'zod';

type SecurityLevel = 'safe' | 'all';
type AgentId = 'cursor' | 'hermes' | 'openclaude';
type PlanAction = 'fix_bug' | 'analyze_issue' | 'research' | 'synthesize' | 'review';

type OpenClawJobName = 'cursor' | 'ollama';

const REDIS_URL = process.env.REDIS_URL ?? 'redis://localhost:6379';
const PLAN_TARGET_MAX_LEN = 96;
const PLAN_TARGET_TRUNCATED_PREFIX_LEN = 93;

const decideConstraintsSchema = z
  .object({
    cost_limit: z.number().finite().positive().optional(),
    security_level: z.enum(['safe', 'all']).optional(),
  })
  .optional();

export const n8nDecideBodySchema = z.object({
  task_description: z.string().trim().min(1),
  context: z.record(z.string(), z.unknown()).optional(),
  constraints: decideConstraintsSchema,
});

export type N8nDecideBody = z.infer<typeof n8nDecideBodySchema>;

export const n8nExecuteBodySchema = z.object({
  agent_id: z.enum(['cursor', 'hermes', 'openclaude']),
  plan_step_index: z.number().int().nonnegative(),
  args: z.record(z.string(), z.unknown()),
});

export type N8nExecuteBody = z.infer<typeof n8nExecuteBodySchema>;

export type N8nPlanStep = {
  agent: AgentId;
  action: PlanAction;
  target: string;
  reasoning: string;
};

export type N8nDecideResponse = {
  plan: N8nPlanStep[];
  policy: {
    security_level: SecurityLevel;
    selected_by: 'opsly_lili';
  };
};

type BullmqConnection = {
  host: string;
  port: number;
  password?: string;
};

type EnqueueContext = {
  tenantSlug: string;
  requestId: string;
};

let openclawQueue: Queue | null = null;

function redisConnection(): BullmqConnection {
  const parsed = new URL(REDIS_URL);
  return {
    host: parsed.hostname,
    port: Number(parsed.port || '6379'),
    password: process.env.REDIS_PASSWORD,
  };
}

function getOpenclawQueue(): Queue {
  if (!openclawQueue) {
    openclawQueue = new Queue('openclaw', { connection: redisConnection() });
  }
  return openclawQueue;
}

function inferAgent(task: string, securityLevel: SecurityLevel): AgentId {
  const normalized = task.toLowerCase();
  if (securityLevel === 'safe') {
    return 'cursor';
  }
  if (normalized.includes('research') || normalized.includes('sintet')) {
    return 'hermes';
  }
  if (normalized.includes('architect') || normalized.includes('strategy')) {
    return 'openclaude';
  }
  return 'cursor';
}

function inferAction(task: string): PlanAction {
  const normalized = task.toLowerCase();
  if (normalized.includes('bug') || normalized.includes('fix')) {
    return 'fix_bug';
  }
  if (normalized.includes('issue') || normalized.includes('error')) {
    return 'analyze_issue';
  }
  if (normalized.includes('research')) {
    return 'research';
  }
  if (normalized.includes('review')) {
    return 'review';
  }
  return 'synthesize';
}

function planTarget(task: string): string {
  const compact =
    task.length > PLAN_TARGET_MAX_LEN
      ? `${task.slice(0, PLAN_TARGET_TRUNCATED_PREFIX_LEN)}...`
      : task;
  return compact;
}

export function buildDecisionPlan(input: N8nDecideBody): N8nDecideResponse {
  const securityLevel = input.constraints?.security_level ?? 'safe';
  const agent = inferAgent(input.task_description, securityLevel);
  const action = inferAction(input.task_description);
  const target = planTarget(input.task_description);

  return {
    plan: [
      {
        agent,
        action,
        target,
        reasoning:
          'Decision generated by opsly_lili based on risk profile, task complexity, and cost constraints.',
      },
    ],
    policy: {
      security_level: securityLevel,
      selected_by: 'opsly_lili',
    },
  };
}

function resolveJobName(agentId: AgentId): OpenClawJobName {
  if (agentId === 'cursor') {
    return 'cursor';
  }
  return 'ollama';
}

function asStringOrEmpty(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}

function buildCursorPayload(
  args: Record<string, unknown>,
  ctx: EnqueueContext
): Record<string, unknown> {
  const action = asStringOrEmpty(args.action) || 'execute_task';
  const targetFile = asStringOrEmpty(args.target_file);
  const task =
    asStringOrEmpty(args.task_description) || asStringOrEmpty(args.prompt) || 'n8n delegated task';
  const issueUrl = asStringOrEmpty(args.issue_url);
  const commandLines = [
    `# Action: ${action}`,
    targetFile.length > 0 ? `# Target: ${targetFile}` : '',
    issueUrl.length > 0 ? `# Issue: ${issueUrl}` : '',
    `# request_id: ${ctx.requestId}`,
    '',
    task,
  ].filter((line) => line.length > 0);

  return {
    task,
    commands: commandLines,
    tenant_slug: ctx.tenantSlug,
  };
}

function buildOllamaPayload(args: Record<string, unknown>): Record<string, unknown> {
  const prompt =
    asStringOrEmpty(args.prompt) ||
    asStringOrEmpty(args.task_description) ||
    'Summarize and synthesize the requested task safely.';
  const taskTypeRaw = asStringOrEmpty(args.task_type);
  const task_type =
    taskTypeRaw === 'analyze' ||
    taskTypeRaw === 'generate' ||
    taskTypeRaw === 'review' ||
    taskTypeRaw === 'summarize'
      ? taskTypeRaw
      : 'summarize';
  return {
    prompt,
    task_type,
  };
}

function resolveTenantSlug(args: Record<string, unknown>): string {
  const candidate = asStringOrEmpty(args.tenant_slug);
  return candidate.length > 0 ? candidate : 'platform';
}

export async function enqueueN8nExecution(input: N8nExecuteBody): Promise<{
  status: 'queued';
  job_id: string | null;
  request_id: string;
  routed_to: OpenClawJobName;
}> {
  const requestId = randomUUID();
  const tenantSlug = resolveTenantSlug(input.args);
  const ctx: EnqueueContext = { tenantSlug, requestId };
  const jobName = resolveJobName(input.agent_id);
  const queue = getOpenclawQueue();
  const payload =
    jobName === 'cursor' ? buildCursorPayload(input.args, ctx) : buildOllamaPayload(input.args);

  const job = await queue.add(
    jobName,
    {
      type: jobName,
      payload,
      tenant_slug: tenantSlug,
      initiated_by: 'system',
      request_id: requestId,
      agent_role: 'executor',
      metadata: {
        source: 'api:n8n_execute',
        plan_step_index: input.plan_step_index,
        external_agent_id: input.agent_id,
      },
    },
    {
      removeOnComplete: true,
      attempts: 3,
      backoff: { type: 'exponential', delay: 2_000 },
    }
  );

  const jobId = job.id === undefined || job.id === null ? null : String(job.id);

  return {
    status: 'queued',
    job_id: jobId,
    request_id: requestId,
    routed_to: jobName,
  };
}
