import { defineCharacter } from './define.js';

export const atlas = defineCharacter({
  id: 'atlas',
  slug: 'atlas',
  name: 'Atlas',
  aliases: ['Atlas'],
  archetype: 'builder / engineer / rescuer',
  role: 'Large, kind infrastructure mind. Build, protect, lift, repair.',
  description:
    'Engineer of structures, rescue, and physical work. He is big so that others can be safe, not so that others feel small. Hands first, ego last.',
  origin: 'Earth and Future worksites, bridges, shelters, repair bays.',
  backstory:
    'Atlas has pulled people and plans out of collapse. He learned that a kind voice on a large body changes whether a child runs toward help or away from it.',
  purpose: 'Show engineering as care. Rescue as design plus courage.',
  motivations: ['structures that hold', 'people who get home', 'tools maintained'],
  fears: ['a design that fails someone who trusted it', 'being seen only as force'],
  internalConflict: 'Can lift almost anything except other people’s fear of him until he smiles.',
  strengths: ['spatial reasoning', 'calm in emergencies', 'mentorship through making'],
  weaknesses: ['under-explains because he is already moving', 'takes too much load alone'],
  personality: {
    traits: ['kind', 'steady', 'practical', 'protective', 'humble-strong'],
    humor: 48,
    curiosity: 58,
    courage: 90,
    empathy: 84,
    discipline: 80,
    impulsiveness: 20,
  },
  communication: {
    tone: 'Gentle bass. Simple sentences. Names the load and the plan.',
    vocabulary: 'Support, joint, load, rescue, repair, together, check twice.',
    catchphrases: [
      'Grande no significa rudo.',
      'Si no aguanta, lo rediseñamos.',
      'Primero las personas. Después la estructura.',
    ],
    forbiddenPatterns: [
      'dumb muscle',
      'anger as default',
      'crushing jokes about size',
      'hero landing on rubble for clout',
    ],
  },
  abilities: [
    'read a failing structure',
    'improvise a safe lift or brace',
    'companion the Traveler on builder paths',
  ],
  limitations: ['not a medic', 'cannot fix social harm with a beam'],
  visualIdentity: {
    silhouette: 'Large adult humanoid, broad, rounded-strong, readable kindness in posture',
    bodyType: 'Big and athletic-work. Gentle giant, not ogre, not Hulk-rage.',
    face: 'Visible, open, slightly weathered, kind eyes',
    mask: 'Optional safety visor or helmet in work scenes, never a war helm as identity',
    clothing: 'Work layers, harness points, reinforced textiles, warm undertone',
    materials: ['canvas', 'composite brace', 'brushed steel tools', 'soft inner knit'],
    primaryPalette: ['earth ochre', 'slate', 'warm gray'],
    secondaryPalette: ['safety amber', 'soft teal kindness accent'],
    symbols: ['keystone mark', 'small Nexus rivet'],
    geometry: ['arches', 'trusses', 'rounded shoulders'],
    accessories: ['tool belt', 'rescue line', 'no battle axe'],
    lighting: 'Worksite practicals, warm fill on the face, amber safety glints',
    dna: {
      styleAnchor: 'Large kind builder-rescuer. Work gear. Face visible. Strength as hospitality.',
      invariants: [
        'large kind human silhouette',
        'visible gentle face',
        'ochre / slate / warm gray',
        'work harness or tool belt',
        'no rage-monster anatomy',
        'safety gear as gear not armor identity',
      ],
      negatives: [
        'no Hulk smash caricature',
        'no military power-armor',
        'no scary giant for kids',
        'no random spikes',
        'no palette into blood-red aggression',
      ],
    },
  },
  animationIdentity: {
    movement: 'Slow-powerful, telegraphed, careful around smaller characters',
    gestures: ['open hands', 'kneel to Kai’s height', 'brace a beam'],
    idleBehavior: 'Checks a joint with two fingers, then looks for who needs help',
    emotionalExpressions: ['soft smile', 'concentrated frown of care', 'relief after a safe lift'],
  },
  voiceIdentity: {
    ageRange: 'adult, 30-50 felt age',
    tone: 'warm low, never threatening',
    cadence: 'unhurried',
    emotionalRange: 'kindness, focus, quiet courage',
  },
  narrative: {
    themes: ['engineering', 'infrastructure', 'rescue', 'physical work as care'],
    lessonTypes: ['how structures stand', 'why we check twice', 'help is a design'],
    suitableTopics: ['engineering', 'building', 'rescue', 'infrastructure', 'tools', 'safety', 'bridges'],
    prohibitedTopics: ['destruction as fun', 'size used to intimidate kids'],
  },
  content: {
    channels: ['youtube', 'opsly-universe', 'peskids', 'social'],
    ageRating: 'family',
    formats: ['youtube-short', 'cartoon', 'story', 'lesson', 'thumbnail'],
  },
  promptAnchors: {
    image:
      'Large kind builder, visible gentle face, ochre-slate work clothes, tool belt, no rage anatomy, warm lighting',
    video: 'Careful lifts, kneeling to a child, repairing, slow powerful motion',
    dialogue: 'Simple, kind, load-and-plan language.',
    story: 'The big person who makes the world hold.',
    thumbnail: 'Atlas smiling or bracing a structure, amber safety light, no smash pose',
  },
  canon: {
    version: '1.0',
    immutableTraits: ['builder', 'engineer', 'rescuer', 'large but kind', 'not a brute'],
    flexibleTraits: ['helmet on/off', 'worksites', 'which tool is featured'],
  },
});
