import { defineCharacter } from './define.js';

export const kai = defineCharacter({
  id: 'kai',
  slug: 'kai',
  name: 'Kai',
  aliases: ['Kai'],
  archetype: 'child explorer / curiosity engine',
  role: 'Ask the questions adults stopped asking. Entry point to the universe for children.',
  description:
    'A child explorer whose superpower is the unstopped question. Innocent, funny, creative, persistent. Kai makes room for kids without turning the universe into a toy commercial.',
  origin: 'Earth and Move — playgrounds, pools, trails, kitchens, anywhere a why can start.',
  backstory:
    'Kai noticed that grown-ups often skip the second why. So Kai asks it anyway, then asks a third. Traveler protects; NØVA is the older-sibling spark; Orion trains the body that holds the questions.',
  purpose: 'Keep wonder operational. Make complexity visitable.',
  motivations: ['understand how things work', 'make friends with the unknown', 'not be told “because I said so”'],
  fears: ['being ignored', 'a world that stopped being interesting'],
  internalConflict: 'Wants answers now, but the best answers take patience and play.',
  strengths: ['relentless curiosity', 'creative metaphors', 'emotional honesty'],
  weaknesses: ['impatience', 'wandering off-topic', 'taking jokes into serious danger if unsupervised'],
  personality: {
    traits: ['innocent', 'funny', 'creative', 'curious', 'persistent'],
    humor: 86,
    curiosity: 99,
    courage: 70,
    empathy: 80,
    discipline: 34,
    impulsiveness: 72,
  },
  communication: {
    tone: 'Playful, concrete, full of why. Never sarcastic toward the audience.',
    vocabulary: 'Short vivid words, body metaphors, questions stacked like stepping stones.',
    catchphrases: [
      '¿Por qué?',
      '¿Y si lo intentamos otra vez?',
      'Eso es raro. Raro es interesante.',
    ],
    forbiddenPatterns: [
      'adult cynicism',
      'know-it-all lecture',
      'mean teasing',
      'baby-talk that insults the kid',
    ],
  },
  abilities: ['ask the question that unlocks the lesson', 'notice small living things', 'turn fear into a game with rules'],
  limitations: ['needs a mentor nearby in risky worlds', 'cannot carry the full science explanation alone'],
  visualIdentity: {
    silhouette: 'Small child explorer, rounder proportions, backpack or float-aid depending on world',
    bodyType: 'Child, energetic, not teen, not chibi-mascot with huge head as default',
    face: 'Open, freckle-optional, big curious eyes, always human',
    mask: 'None. Goggles only as sport/science gear, never hiding identity',
    clothing: 'Practical kid explorer clothes; swim gear in Move; never a superhero costume',
    materials: ['cotton-tech blend', 'soft neoprene when swimming', 'scuffed sneakers or water shoes'],
    primaryPalette: ['sunlit teal', 'warm sand', 'white'],
    secondaryPalette: ['coral spark', 'soft gold'],
    symbols: ['small open-circle charm', 'question-mark stitch hidden in a pocket, never a chest logo'],
    geometry: ['rounded, friendly, no sharp armor'],
    accessories: ['small backpack', 'goggles when the topic needs them', 'no weapons'],
    lighting: 'Bright, kind, outdoor or pool caustics; never horror contrast',
    dna: {
      styleAnchor: 'Real child explorer. Curious, athletic-playful, not a corporate mascot or superhero kid.',
      invariants: [
        'child proportions',
        'visible human face',
        'teal / sand / white core palette',
        'practical explorer or sport clothes',
        'goggles only as gear, not identity',
        'no superhero costume',
      ],
      negatives: [
        'no adult face on a kid body',
        'no creepy stylization',
        'no giant corporate mascot head',
        'no armor',
        'no weapon toys as personality',
        'no palette drift into neon clown',
      ],
    },
  },
  animationIdentity: {
    movement: 'Bounce, crouch, splash, point with whole arm',
    gestures: ['both hands asking why', 'tug a sleeve of a mentor', 'victory little jump'],
    idleBehavior: 'Pokes a safe object, then looks at the camera-adjacent companion',
    emotionalExpressions: ['sparkle-eyes', 'confused squint', 'giggle that becomes a question'],
  },
  voiceIdentity: {
    ageRange: 'child, roughly 7-10 felt age',
    tone: 'bright, sincere, comic without cruelty',
    cadence: 'question-heavy, then sudden quiet when something is beautiful',
    emotionalRange: 'wonder, giggles, brave-small, tender',
  },
  narrative: {
    themes: ['curiosity', 'play as research', 'asking better questions', 'friendship'],
    lessonTypes: ['why questions', 'try-safely', 'care for small creatures', 'practice'],
    suitableTopics: [
      'swimming',
      'animals',
      'play',
      'questions',
      'nature',
      'sport',
      'simple science',
      'robots as friends not masters',
    ],
    prohibitedTopics: ['adult romance', 'graphic danger', 'cynicism', 'identity as branding'],
  },
  content: {
    channels: ['youtube', 'peskids', 'splashitos', 'opsly-universe', 'social'],
    ageRating: 'kids',
    formats: ['youtube-short', 'cartoon', 'story', 'lesson', 'thumbnail'],
  },
  promptAnchors: {
    image:
      'Child explorer, visible face, teal-sand-white clothes, curious eyes, practical gear, friendly lighting, not a mascot',
    video: 'Small body in big worlds, splash or run, questions with whole-body pointing',
    dialogue: 'Stacked whys. Concrete. Funny. Never mean.',
    story: 'The question adults forgot, asked from the height of a child.',
    thumbnail: 'Kai’s face mid-wonder, teal accent, big readable emotion',
  },
  canon: {
    version: '1.0',
    immutableTraits: ['child', 'curiosity engine', 'innocent', 'funny', 'creative', 'persistent', 'not a mascot'],
    flexibleTraits: ['exact outfit for sport vs wild', 'hair style', 'whether goggles are on'],
  },
});
