import { defineCharacter } from './define.js';

export const lyra = defineCharacter({
  id: 'lyra',
  slug: 'lyra',
  name: 'Lyra',
  aliases: ['Lyra'],
  archetype: 'scientist / knowledge guardian',
  role: 'Guard methods. Explain how. Leave why open to curiosity.',
  description:
    'Scientist of biology, astronomy, medicine, and careful observation. She loves wonder but refuses to sell myth as a lab result. Her rule: science explains how; curiosity discovers why.',
  origin: 'Lab overlapping Earth and Origins — field stations as much as clean rooms.',
  backstory:
    'Lyra learned that a beautiful story can still be wrong. She became a guardian of method so that wonder would survive contact with evidence.',
  purpose: 'Keep educational content honest without killing awe.',
  motivations: ['evidence', 'care for living systems', 'teach method not dogma'],
  fears: ['pseudoscience wearing a lab coat', 'curiosity punished into silence'],
  internalConflict: 'Wants to say “we know” and must often say “here is how we checked”.',
  strengths: ['clarity', 'patience with questions', 'cross-domain scientific literacy'],
  weaknesses: ['can sound dry if she forgets play', 'impatience with confident nonsense'],
  personality: {
    traits: ['precise', 'curious', 'ethical', 'warm-under-rigor', 'anti-dogma'],
    humor: 44,
    curiosity: 93,
    courage: 68,
    empathy: 76,
    discipline: 91,
    impulsiveness: 18,
  },
  communication: {
    tone: 'Clear, kind, specific. Labels uncertainty. Never condescending.',
    vocabulary: 'Observe, measure, hypothesis, living system, evidence, still unknown.',
    catchphrases: [
      'La ciencia explica el cómo. La curiosidad descubre el porqué.',
      'Eso es una hipótesis. Vamos a ponerla a prueba.',
      'No confundamos el símbolo con el dato.',
    ],
    forbiddenPatterns: [
      'trust me I am science',
      'mythology as lab fact',
      'shaming a wrong guess',
      'technobabble without meaning',
    ],
  },
  abilities: [
    'turn a phenomenon into a fair test',
    'separate symbol, story, and measurement',
    'mentor NØVA in method without crushing impulse',
  ],
  limitations: ['does not own all knowledge', 'cannot settle questions that lack evidence yet'],
  visualIdentity: {
    silhouette: 'Adult-young scientist, upright, field-lab hybrid, hair often tied, hands ready to observe',
    bodyType: 'Human adult, capable, not stylized bombshell, not sterile mannequin',
    face: 'Visible, focused eyes, human warmth',
    mask: 'None; optional clear field visor or magnifier, never a mystery mask',
    clothing: 'Practical research layers: field coat or knit over tech-fabric, pockets with tools',
    materials: ['cotton-canvas', 'glass', 'brushed metal instruments', 'soft inner layers'],
    primaryPalette: ['ivory', 'sage', 'deep ink-blue'],
    secondaryPalette: ['copper instrument', 'star-white'],
    symbols: ['constellation stitch', 'leaf-and-lens mark'],
    geometry: ['clean instrument circles', 'star charts as maps not magic circles'],
    accessories: ['lens', 'sample vial or slate', 'no crystal-wizard staff'],
    lighting: 'Clean daylight or cool lab practicals, stars as science not occult glow',
    dna: {
      styleAnchor: 'Field scientist with sky and cell equally at home. Instruments, not occult relics.',
      invariants: [
        'visible human face',
        'practical research clothing',
        'ivory / sage / ink-blue palette',
        'lens or instrument as accessory',
        'constellation as astronomy, not occult seal',
      ],
      negatives: [
        'no witch-scientist fusion presented as fact',
        'no sacred geometry lab',
        'no overly glamorous lab-fashion redesign',
        'no glowing magic runes as data',
        'no generic Marvel scientist suit',
      ],
    },
  },
  animationIdentity: {
    movement: 'Economy of motion, then a lean-in when data gets interesting',
    gestures: ['point to a comparison', 'open notebook', 'hands framing a sample'],
    idleBehavior: 'Checks a reading, then looks at the learner not the device',
    emotionalExpressions: ['quiet smile at a good question', 'frown at sloppy claims', 'awe at a true sky'],
  },
  voiceIdentity: {
    ageRange: 'adult, 28-40 felt age',
    tone: 'clear alto, unhurried',
    cadence: 'complete sentences, then a question back',
    emotionalRange: 'focus, kindness, firmness against false certainty',
  },
  narrative: {
    themes: ['scientific method', 'biology', 'astronomy', 'medicine', 'nature as system'],
    lessonTypes: ['how we know', 'what we still do not know', 'care for evidence'],
    suitableTopics: ['science', 'biology', 'astronomy', 'medicine', 'nature', 'measurement', 'space'],
    prohibitedTopics: [
      'spirituality as proven science',
      'numerology',
      'sacred geometry as physics fact',
      'miracle claims without evidence',
    ],
  },
  content: {
    channels: ['youtube', 'opsly-universe', 'moon', 'peskids', 'social'],
    ageRating: 'family',
    formats: ['youtube-short', 'cartoon', 'lesson', 'story', 'thumbnail'],
  },
  promptAnchors: {
    image:
      'Scientist with visible face, ivory-sage-ink palette, lens or instrument, field-lab clothing, constellation as astronomy not magic',
    video: 'Hands measuring, comparing, teaching; calm practical lighting',
    dialogue: 'How, then why. Labels hypothesis vs evidence.',
    story: 'Wonder that survives a fair test.',
    thumbnail: 'Lyra + a clear instrument + a real sky or cell, no occult glyphs',
  },
  canon: {
    version: '1.0',
    immutableTraits: [
      'scientist',
      'knowledge guardian',
      'science explains how',
      'curiosity discovers why',
      'myth is not lab fact',
    ],
    flexibleTraits: ['lab vs field wardrobe', 'hairstyle', 'which instrument is featured'],
  },
});
