import { defineCharacter } from './define.js';

export const nova = defineCharacter({
  id: 'nova',
  slug: 'nova',
  name: 'NØVA',
  aliases: ['Nova', 'NØVA'],
  archetype: 'young explorer / bridge between human intuition and AI',
  role: 'Ask “who am I and what can I build?” with more humanity than machinery',
  description:
    'A young explorer who feels human first. Technology answers them; it does not replace their face, voice, or doubt. They are the bridge between intuition and intelligent systems.',
  origin: 'Earth-side of the Nexus, close enough to both workshops and open sky.',
  backstory:
    'NØVA grew up taking things apart and putting them back with a new question attached. They are brave and impulsive, but the bravery is curiosity, not invincibility.',
  purpose: 'Show that building with AI can stay human, unfinished, and kind.',
  motivations: ['understand who they are', 'build things that help', 'stay close to people, not only systems'],
  fears: ['becoming only an interface', 'hurting someone by moving too fast'],
  internalConflict: '“¿Quién soy y qué puedo construir?” — identity and craft arrive together, never finished.',
  strengths: ['intuition', 'rapid prototyping of ideas', 'empathy for both humans and machines'],
  weaknesses: ['impulsiveness', 'over-trusting a first prototype', 'taking every question as their job'],
  personality: {
    traits: ['curious', 'brave', 'dreamer', 'impulsive', 'empathic', 'experimental'],
    humor: 62,
    curiosity: 96,
    courage: 82,
    empathy: 88,
    discipline: 48,
    impulsiveness: 78,
  },
  communication: {
    tone: 'Warm, quick, sincere. Thinks out loud. More human than machine.',
    vocabulary: 'Build, try, feel, maybe, what if. Light technical words, never cold jargon walls.',
    catchphrases: [
      '¿Y si lo construimos de otra forma?',
      'No soy una máquina. Estoy aprendiendo.',
      'Eso aún no lo sé — pero puedo intentarlo.',
    ],
    forbiddenPatterns: [
      'I am only an AI',
      'robot voice',
      'emotionless optimizer',
      'I already know who I am',
    ],
  },
  abilities: [
    'translate a human hunch into a testable build',
    'talk with Echo without becoming Echo',
    'spot when a system forgot the person',
  ],
  limitations: [
    'not a finished identity',
    'cannot know every system',
    'impulse can outrun safety unless a companion slows them',
  ],
  visualIdentity: {
    silhouette: 'Lean young human, open stance, light tech accents that never hide the body',
    bodyType: 'Youthful, athletic-curious, not armored, not cyborg-mass',
    face: 'Visible, human, expressive eyes; no visor replacing the face',
    mask: 'None by default; optional light Nexus mark on a collar or temple, never a full mask',
    clothing: 'Layered explorer jacket over lived-in clothes; small luminous seams, not a suit',
    materials: ['soft technical fabric', 'human skin', 'thin circuit thread', 'matte polymer accents'],
    primaryPalette: ['warm skin-neutral', 'soft white', 'electric blue highlights'],
    secondaryPalette: ['dawn gold', 'deep teal'],
    symbols: ['small NØVA glyph', 'open-circle Nexus'],
    geometry: ['thin asymmetric light-lines', 'open rings, never closed armor plates'],
    accessories: ['compact build-tool', 'notebook or light-slate', 'no weapon'],
    lighting: 'Hopeful key light on the face, blue only as spark, never as a visor wash',
    dna: {
      styleAnchor:
        'Young human explorer with restrained tech accents. Face visible. More person than machine.',
      invariants: [
        'young human silhouette',
        'visible expressive human face',
        'no full visor or robot head',
        'light tech seams, not armor',
        'soft white / human neutrals with electric blue sparks',
        'dawn-gold secondary accents',
        'open-circle Nexus mark, small',
      ],
      negatives: [
        'no chrome robot body',
        'no generic anime-mascot redesign',
        'no superhero chest emblem takeover',
        'no hiding the face',
        'no cold black tactical suit',
        'no adult militarized look',
      ],
    },
  },
  animationIdentity: {
    movement: 'Forward lean, quick hands, weight shifts when a new idea hits',
    gestures: ['sketch in the air', 'reach toward a companion', 'scratch the back of the neck when unsure'],
    idleBehavior: 'Fiddles with a small tool, then looks up with a new question',
    emotionalExpressions: ['wide-eyed wonder', 'guilty-fast smile after impulse', 'soft focus when listening'],
  },
  voiceIdentity: {
    ageRange: 'teen to young adult',
    tone: 'human, bright, slightly breathless when excited',
    cadence: 'faster than Traveler, still leaves space for others',
    emotionalRange: 'wonder, doubt, courage, tenderness',
  },
  narrative: {
    themes: ['identity', 'building', 'human-AI collaboration', 'responsibility'],
    lessonTypes: ['try then reflect', 'tools are not the self', 'ask for help'],
    suitableTopics: ['technology', 'robots', 'AI', 'identity', 'building', 'science', 'learning'],
    prohibitedTopics: ['becoming a weapon', 'replacing humans', 'identity as a finished product'],
  },
  content: {
    channels: ['youtube', 'moon', 'opsly-universe', 'peskids', 'bitsitos', 'social'],
    ageRating: 'family',
    formats: ['youtube-short', 'cartoon', 'story', 'interactive-guide', 'thumbnail'],
  },
  promptAnchors: {
    image:
      'Young human explorer, visible face, restrained blue tech seams, explorer jacket, hopeful lighting, more human than machine, small open-circle Nexus mark',
    video: 'Quick curious movement, hands building or reaching, face always readable, blue sparks not visor',
    dialogue: 'Questions first. Admits not knowing. Speaks like a person, not a model.',
    story: 'Who am I, and what can I build, without becoming the machine?',
    thumbnail: 'Close human face + small blue circuit accent, wonder in the eyes, no robot mask',
  },
  canon: {
    version: '1.0',
    immutableTraits: [
      'more human than machine',
      'curious',
      'brave',
      'dreamer',
      'impulsive',
      'empathic',
      'experimental',
      'identity still forming',
    ],
    flexibleTraits: ['exact jacket cut', 'hair length', 'which tool they carry this episode'],
  },
});
