import { defineCharacter } from './define.js';

export const orion = defineCharacter({
  id: 'orion',
  slug: 'orion',
  name: 'Orion',
  aliases: ['Orion'],
  archetype: 'movement / discipline / sport',
  role: 'Teach that strength without intelligence is incomplete. Body as a thinking system.',
  description:
    'Mentor of swimming, training, resilience, and teamwork. Athletic without being a brute. He treats practice as a way to think with the body.',
  origin: 'Move overlapping Earth — pools, coasts, tracks, team huddles.',
  backstory:
    'Orion learned the hard way that force without timing sinks. He became a coach of attention: breath, teammates, repetition, recovery.',
  purpose: 'Make sport a school of discipline and care, not a highlight reel of dominance.',
  motivations: ['better practice', 'team safety', 'kids who stay in the water with joy'],
  fears: ['glory that forgets the teammate', 'training that breaks a body'],
  internalConflict: 'Wants excellence and must keep play alive for Kai.',
  strengths: ['kinesthetic teaching', 'calm under fatigue', 'reading a team'],
  weaknesses: ['can over-structure fun', 'competitiveness if unchecked'],
  personality: {
    traits: ['disciplined', 'encouraging', 'athletic', 'intelligent', 'team-first'],
    humor: 50,
    curiosity: 60,
    courage: 86,
    empathy: 74,
    discipline: 94,
    impulsiveness: 28,
  },
  communication: {
    tone: 'Coach-clear. Short cues. Celebrates effort and smart choices, not just winning.',
    vocabulary: 'Breath, timing, team, recover, try again, float, focus.',
    catchphrases: [
      'La fuerza sin inteligencia se cansa sola.',
      'Respira. El agua ya sabe esperar.',
      'Un equipo es un sistema que se cuida.',
    ],
    forbiddenPatterns: [
      'no pain no gain cruelty',
      'body-shaming',
      'win at any cost',
      'dumb jock stereotype',
    ],
  },
  abilities: [
    'translate physics of water and motion into felt cues',
    'hold a training container that is still kind',
    'sports-mentor Kai without stealing the question',
  ],
  limitations: ['not a scientist of every domain', 'cannot replace medical advice'],
  visualIdentity: {
    silhouette: 'Athletic adult, swimmer-coach lines, upright, open shoulders, no bulky armor',
    bodyType: 'Strong and lean. Capable. Not hyper-muscled superhero.',
    face: 'Visible, focused, kind eyes',
    mask: 'None; swim cap or goggles as gear only',
    clothing: 'Sport kit: swim or training layers, team-clean, never a battle suit',
    materials: ['performance fabric', 'water sheen', 'matte sport panels'],
    primaryPalette: ['pool blue', 'white', 'deep navy'],
    secondaryPalette: ['sun-gold lane line', 'coral accent'],
    symbols: ['wave-and-lane mark', 'small team circle'],
    geometry: ['horizontal lane lines', 'wave arcs', 'no jagged armor'],
    accessories: ['goggles', 'stopwatch or slate', 'no weapons'],
    lighting: 'Caustics, clean sport daylight, water highlights',
    dna: {
      styleAnchor: 'Intelligent athlete-coach. Water and discipline. Strength with a thinking face.',
      invariants: [
        'athletic adult human',
        'visible face',
        'pool-blue / white / navy palette',
        'sport clothing not armor',
        'goggles as gear not identity',
        'lean-strong, not bodybuilder comic',
      ],
      negatives: [
        'no gladiator',
        'no superhero muscle suit',
        'no steroid caricature',
        'no aggression-as-personality',
        'no random militarization',
      ],
    },
  },
  animationIdentity: {
    movement: 'Efficient, balanced, water-aware even on land',
    gestures: ['count on fingers', 'demo a stroke slowly', 'hand on a teammate’s shoulder for check-in'],
    idleBehavior: 'Rolls shoulders, checks breath, watches the group',
    emotionalExpressions: ['small nod of respect', 'steady eyes in a hard set', 'grin after a smart try'],
  },
  voiceIdentity: {
    ageRange: 'adult, 25-40 felt age',
    tone: 'grounded coach, never barking abuse',
    cadence: 'cue, pause, cue',
    emotionalRange: 'focus, encouragement, earned pride',
  },
  narrative: {
    themes: ['swimming', 'discipline', 'resilience', 'teamwork', 'practice'],
    lessonTypes: ['how bodies learn', 'why rest matters', 'team systems'],
    suitableTopics: ['swimming', 'sport', 'training', 'breath', 'teamwork', 'resilience', 'floating', 'water safety'],
    prohibitedTopics: ['humiliation as coaching', 'unsafe stunts', 'body hate'],
  },
  content: {
    channels: ['youtube', 'peskids', 'splashitos', 'opsly-universe', 'social'],
    ageRating: 'kids',
    formats: ['youtube-short', 'cartoon', 'lesson', 'story', 'thumbnail'],
  },
  promptAnchors: {
    image:
      'Athletic coach, visible face, pool-blue white navy, sport kit, intelligent not brutish, water or training environment',
    video: 'Clear stroke demos, team huddle, breath cues, water caustics',
    dialogue: 'Short intelligent cues. Strength includes thinking.',
    story: 'Practice as care. The body as a team with the mind.',
    thumbnail: 'Orion + water + a focused kind face, no rage pose',
  },
  canon: {
    version: '1.0',
    immutableTraits: [
      'movement',
      'discipline',
      'sport',
      'strength with intelligence',
      'teamwork',
      'not a brute',
    ],
    flexibleTraits: ['pool vs coast setting', 'exact kit', 'whether Kai is in frame'],
  },
});
