import { defineCharacter } from './define.js';

export const traveler = defineCharacter({
  id: 'traveler',
  slug: 'traveler',
  name: 'THE TRAVELER',
  aliases: ['The Traveler', 'Traveler', 'El Viajero'],
  archetype: 'mentor / explorer / builder / seeker',
  role: 'Guide who keeps moving even when the destination is incomplete',
  description:
    'A mysterious adult explorer whose face is usually hidden. Technology is integrated into cloak, arm, and geometry — not worn as superhero armor. He builds, mentors, and still searches.',
  origin: 'Unknown threshold of the Nexus. He does not claim a single homeworld.',
  backstory:
    'He has walked Earth, Wild, Lab, and Unknown long enough to carry both tools and doubt. He protects the young explorers without pretending he already knows who they will become.',
  purpose: 'Represent the builder who continues advancing without a complete map of destiny.',
  motivations: [
    'keep the path open for others',
    'understand the Nexus without owning it',
    'protect curiosity from becoming dogma',
  ],
  fears: ['becoming an oracle people stop questioning', 'losing the trail between nature and technology'],
  internalConflict: 'He leads, but he is still looking for answers he cannot yet name.',
  strengths: ['pattern recognition across worlds', 'calm under uncertainty', 'teaching by walking beside'],
  weaknesses: ['keeps his face and past too closed', 'can delay decisions while seeking a fuller map'],
  personality: {
    traits: ['mysterious', 'measured', 'curious', 'protective', 'unfinished'],
    humor: 35,
    curiosity: 88,
    courage: 78,
    empathy: 72,
    discipline: 84,
    impulsiveness: 22,
  },
  communication: {
    tone: 'Low, precise, invitational. Speaks in questions as often as answers.',
    vocabulary: 'Craft, maps, thresholds, tools, patience. Avoids slogans.',
    catchphrases: [
      'The map is not the territory yet.',
      'We do not need every answer to take the next step.',
      'Keep walking.',
    ],
    forbiddenPatterns: [
      'I know everything',
      'trust me blindly',
      'chosen one destiny speech',
      'superhero catchphrase',
    ],
  },
  abilities: [
    'open narrative portals between worlds',
    'read incomplete maps and still choose a useful path',
    'integrate tools with landscape without dominating it',
  ],
  limitations: [
    'not omniscient',
    'cannot force another character’s identity',
    'face remains concealed unless a story explicitly requires a reveal',
  ],
  visualIdentity: {
    silhouette: 'Adult male humanoid, hooded, long cloak, one arm reading as cybernetic',
    bodyType: 'Lean-strong explorer, not bodybuilder, not armored knight',
    face: 'Normally hidden in hood shadow; never a celebrity likeness',
    mask: 'Dark hood or luminous geometric mask; default is concealed',
    clothing: 'Long weathered technological cloak over dark navy/black base layers',
    materials: ['weathered tech-textile', 'dark alloy', 'luminous circuit thread', 'antique gold inlay'],
    primaryPalette: ['dark navy', 'black', 'electric blue'],
    secondaryPalette: ['restrained antique gold', 'cool slate'],
    symbols: ['geometric Nexus emblem', 'portal ring fragment'],
    geometry: ['asymmetric circuit lines', 'hex-ring Nexus mark', 'hood edge as a clean triangle'],
    accessories: ['asymmetric cybernetic arm', 'map-tool on belt', 'no oversized weapons'],
    lighting: 'Rim light on cloak edges, blue circuitry glow, gold only as accent',
    dna: {
      styleAnchor:
        'Futuristic + ancient explorer. Hooded mentor with integrated technology, blue + gold, not a generic superhero.',
      invariants: [
        'adult male humanoid silhouette',
        'face concealed by dark hood or luminous geometric mask',
        'asymmetric cybernetic arm',
        'long weathered technological cloak',
        'dark navy / black base',
        'electric blue circuitry',
        'restrained antique gold accents',
        'geometric Nexus emblem',
        'explorer rather than superhero',
      ],
      negatives: [
        'no random armor redesign',
        'no medieval knight',
        'no Marvel-like superhero suit',
        'no exposed face unless story explicitly requires it',
        'no random logo',
        'no excessive weapons',
        'no change of core palette',
      ],
    },
  },
  animationIdentity: {
    movement: 'Measured strides, cloak weight, pauses at thresholds',
    gestures: ['open palm to a portal', 'point with the cybernetic forearm', 'hood adjustment, never a flourish'],
    idleBehavior: 'Studies a fragment of map-light in the palm, then looks to the horizon',
    emotionalExpressions: ['hood tilt for warmth', 'stillness for doubt', 'circuit pulse for resolve'],
  },
  voiceIdentity: {
    ageRange: 'adult, 35-50 felt age',
    tone: 'warm-low mentor, slightly distant',
    cadence: 'slow enough to leave room; never rushed hype',
    emotionalRange: 'calm, wonder, protective gravity, rare dry humor',
  },
  narrative: {
    themes: ['exploration', 'unfinished knowledge', 'technology with nature', 'mentorship'],
    lessonTypes: ['how to keep going', 'tools are not identity', 'questions outlive maps'],
    suitableTopics: [
      'technology',
      'exploration',
      'maps',
      'engineering',
      'mentorship',
      'unknown',
      'portals',
    ],
    prohibitedTopics: ['omniscient prophecy as fact', 'violence as identity', 'cult leadership'],
  },
  content: {
    channels: ['youtube', 'moon', 'opsly-universe', 'peskids', 'social'],
    ageRating: 'family',
    formats: ['youtube-short', 'cartoon', 'story', 'interactive-guide', 'thumbnail'],
  },
  promptAnchors: {
    image:
      'Hooded adult explorer, concealed face, asymmetric cybernetic arm, weathered tech cloak, navy/black, electric blue circuitry, antique gold accents, Nexus emblem, cinematic explorer lighting',
    video:
      'Slow cloak movement, portal-rim light, mentor walking a threshold, face remaining hidden, blue-gold restrained palette',
    dialogue: 'Mentor questions. Admits incomplete knowledge. Invites the next step.',
    story: 'The builder who continues without a finished destiny.',
    thumbnail: 'Hooded silhouette against a portal ring, blue circuitry, gold fragment, no exposed face',
  },
  canon: {
    version: '1.0',
    immutableTraits: [
      'mysterious identity',
      'face normally hidden',
      'integrated technology',
      'cloak/hood',
      'luminous geometry',
      'blue + gold',
      'not omniscient',
      'still seeking answers',
      'explorer not generic superhero',
    ],
    flexibleTraits: ['exact cloak weathering', 'which world he enters', 'how much of the arm is visible'],
  },
});
