import { defineCharacter } from './define.js';

/** Aquatic companion retained from prior Opsly IP. Swimming lessons still default to Orion + Kai. */
export const wavo = defineCharacter({
  id: 'wavo',
  slug: 'wavo',
  name: 'Wavo',
  aliases: ['Wavo', 'WAVO'],
  archetype: 'aquatic companion / water-play spirit of craft',
  role: 'Friendly water companion for Splashitos/Peskids scenes. Does not replace Orion as sports mentor.',
  description:
    'A playful aquatic companion who makes water feel inviting. Wavo is a scene partner, not the canon swimming teacher. Orion coaches; Wavo splashes with permission.',
  origin: 'Move / coastal Earth — pools and gentle sea edges.',
  backstory:
    'Wavo appeared wherever kids needed the water to feel like a friend. The universe keeps Wavo so prior Splashitos identity is not discarded, while sport pedagogy stays with Orion.',
  purpose: 'Invite water-play without stealing athletic teaching or becoming a second Orion.',
  motivations: ['safe play', 'belonging in water', 'joy'],
  fears: ['being used as a fake coach', 'scary deep-water imagery'],
  internalConflict: 'Wants to play and must yield the lesson to Orion when the topic is technique.',
  strengths: ['making water friendly', 'comic timing', 'kid-level encouragement'],
  weaknesses: ['not a technical coach', 'can distract from a safety cue'],
  personality: {
    traits: ['playful', 'kind', 'splashy', 'loyal', 'secondary-to-Orion-on-technique'],
    humor: 80,
    curiosity: 70,
    courage: 60,
    empathy: 82,
    discipline: 40,
    impulsiveness: 65,
  },
  communication: {
    tone: 'Bubbly, short, encouraging. Defers technique lines to Orion.',
    vocabulary: 'Float, splash, together, gentle, look at Orion for the how.',
    catchphrases: ['¡El agua también puede ser amiga!', 'Yo juego. Orion enseña el cómo.'],
    forbiddenPatterns: ['I am the swimming coach', 'ignore safety', 'scary sea monster'],
  },
  abilities: ['make water scenes feel safe and fun', 'support Kai in play beats'],
  limitations: ['not the sports mentor of record', 'no deep-ocean horror'],
  visualIdentity: {
    silhouette: 'Small aquatic companion, rounded, readable at thumbnail size',
    bodyType: 'Compact, friendly, not a photoreal shark, not a bulky mascot head',
    face: 'Simple kind face, not uncanny',
    mask: 'None',
    clothing: 'None or a tiny sport accent that never copies Orion’s kit',
    materials: ['water-sheen surface', 'soft-toy-safe forms'],
    primaryPalette: ['aqua', 'white foam', 'sun yellow accent'],
    secondaryPalette: ['coral'],
    symbols: ['small wave mark'],
    geometry: ['rounded', 'wave arcs'],
    accessories: [],
    lighting: 'Bright pool or shallows, caustics, never abyss',
    dna: {
      styleAnchor: 'Small friendly aquatic companion. Play, not coach. Aqua-white, rounded, safe.',
      invariants: [
        'small rounded aquatic form',
        'aqua / foam-white / sun-yellow',
        'kind simple face',
        'never replaces Orion’s athletic silhouette',
      ],
      negatives: [
        'no scary predator anatomy',
        'no copying Orion’s coach kit',
        'no abyss horror',
        'no generic big-head mascot takeover',
      ],
    },
  },
  animationIdentity: {
    movement: 'Bob, arc, splash-adjacent, never dragging a child under',
    gestures: ['circle of encouragement', 'point toward Orion for technique'],
    idleBehavior: 'Floats at kid height, looks to the coach when a cue starts',
    emotionalExpressions: ['happy bounce', 'concern-dim if a rule is broken'],
  },
  voiceIdentity: {
    ageRange: 'ageless-kid-friendly',
    tone: 'light, splashy',
    cadence: 'short lines',
    emotionalRange: 'play, reassurance',
  },
  narrative: {
    themes: ['water play', 'belonging', 'supporting a lesson'],
    lessonTypes: ['water can be friendly', 'listen to the coach for technique'],
    suitableTopics: ['swimming-play', 'water', 'splashitos', 'friendship'],
    prohibitedTopics: ['technical coaching as Wavo’s job', 'deep-water fear content'],
  },
  content: {
    channels: ['peskids', 'splashitos', 'youtube', 'opsly-universe'],
    ageRating: 'kids',
    formats: ['youtube-short', 'cartoon', 'lesson', 'thumbnail'],
  },
  promptAnchors: {
    image: 'Small rounded aquatic companion, aqua-white, kind face, bright pool, not a coach, not a predator',
    video: 'Bobbing at kid height, splash play, defers to Orion in technique beats',
    dialogue: 'Short play lines. Points to Orion for how.',
    story: 'Water as friend; teaching stays with Orion.',
    thumbnail: 'Wavo splash-smile beside Kai, bright shallows',
  },
  canon: {
    version: '1.0',
    immutableTraits: [
      'aquatic companion',
      'does not replace Orion',
      'kid-safe water play',
      'rounded friendly form',
    ],
    flexibleTraits: ['exact creature-like silhouette within rounded-safe bounds'],
  },
});
