#!/bin/bash

# Split terminal into 4 panes to monitor Phase 1 test

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║              PHASE 1 TEST - MONITORING SETUP                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Run these 4 commands in SEPARATE terminals:"
echo ""
echo "┌─ Terminal A ─ Health Check ──────────────────────────────────┐"
echo "│                                                               │"
echo "  while true; do clear; echo '=== HEALTH ==='; curl -s http://localhost:3011/health | jq . 2>/dev/null || echo 'WAITING...'; curl -s http://localhost:5001/health | jq . 2>/dev/null || echo 'CursorAgent WAITING...'; sleep 2; done"
echo ""
echo "│                                                               │"
echo "└───────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─ Terminal B ─ Metadata & Files ───────────────────────────────┐"
echo "│                                                               │"
echo "  cd /home/user/opsly && watch -n 1 'echo \"=== METADATA ===\"; cat .cursor/prompts/.metadata.json 2>/dev/null | jq . || echo \"No metadata yet\"; echo \"\"; echo \"=== RESPONSES ===\"; ls -la .cursor/responses/ 2>/dev/null | tail -5 || echo \"No responses yet\"'"
echo ""
echo "│                                                               │"
echo "└───────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─ Terminal C ─ Test Prompt ────────────────────────────────────┐"
echo "│                                                               │"
echo "  cat /home/user/opsly/.cursor/prompts/test-local-cursor-phase1.md"
echo ""
echo "│                                                               │"
echo "└───────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─ Terminal D ─ Logs (choose one) ──────────────────────────────┐"
echo "│                                                               │"
echo "  tail -f /tmp/watcher.log              # LocalPromptWatcher"
echo "  tail -f /tmp/orchestrator-run.log     # Orchestrator"
echo "  tail -f /tmp/cursor-agent-service.log # CursorAgent Service"
echo "  tail -f /tmp/autocommit.log           # Git AutoCommit"
echo ""
echo "│                                                               │"
echo "└───────────────────────────────────────────────────────────────┘"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "When Cursor executes:"
echo "  ✅ File: src/test-local-greeting.ts should appear"
echo "  ✅ Git: new commit should show in git log"
echo "  ✅ Metadata: should show status='completed'"
echo ""
