import { z } from "zod";
import { opslyFetch } from "../lib/api-client.js";
import { writeActivePrompt } from "../lib/github.js";
import type { ToolDefinition } from "../types/index.js";

const PLATFORM_SERVICE_ALIASES = new Set(["api", "platform", "opsly", "core"]);
const SAFE_IDENTIFIER = /^[a-zA-Z0-9][a-zA-Z0-9_.-]{1,127}$/;

type HealthToolResult = {
  ok: boolean;
  scope: "platform" | "tenant";
  service: string;
  data: unknown;
};

type RestartToolResult = {
  ok: boolean;
  queued: true;
  container: string;
  message: string;
};

function assertSafeIdentifier(value: string, label: string): string {
  const trimmed = value.trim();
  if (!SAFE_IDENTIFIER.test(trimmed)) {
    throw new Error(
      `Invalid ${label}: use only letters, numbers, dot, dash or underscore`,
    );
  }
  return trimmed;
}

function resolveHealthTarget(service?: string): {
  scope: "platform" | "tenant";
  service: string;
  path: string;
} {
  const raw = service?.trim();
  if (!raw || PLATFORM_SERVICE_ALIASES.has(raw.toLowerCase())) {
    return {
      scope: "platform",
      service: raw && raw.length > 0 ? raw : "platform",
      path: "/api/health",
    };
  }

  const tenantSlug = assertSafeIdentifier(raw.toLowerCase(), "service");
  return {
    scope: "tenant",
    service: tenantSlug,
    path: `/api/portal/health?slug=${encodeURIComponent(tenantSlug)}`,
  };
}

function buildRestartPrompt(container: string): string {
  return [
    "# restart_container generated by OpenClaw MCP",
    `# container: ${container}`,
    `docker ps --format '{{.Names}}' | grep -Fx '${container}' >/dev/null`,
    `docker restart '${container}'`,
  ].join("\n");
}

export const opsStubsTools: [
  ToolDefinition<{ service?: string }, HealthToolResult>,
  ToolDefinition<{ container?: string }, RestartToolResult>,
] = [
  {
    name: "check_service_health",
    description: "Comprueba la salud de la plataforma o de un tenant por slug.",
    inputSchema: z.object({ service: z.string().optional() }),
    handler: async ({ service }) => {
      const target = resolveHealthTarget(service);
      const data = await opslyFetch(target.path);
      return {
        ok: true,
        scope: target.scope,
        service: target.service,
        data,
      };
    },
  },
  {
    name: "restart_container",
    description:
      "Solicita reinicio de un contenedor Docker via ACTIVE-PROMPT con validacion estricta.",
    inputSchema: z.object({ container: z.string().optional() }),
    handler: async ({ container }) => {
      if (!container) {
        throw new Error("container is required");
      }

      const safeContainer = assertSafeIdentifier(container, "container");
      await writeActivePrompt(buildRestartPrompt(safeContainer));

      return {
        ok: true,
        queued: true,
        container: safeContainer,
        message: "restart request written to docs/ACTIVE-PROMPT.md",
      };
    },
  },
];
