import { requireAdminToken } from '../../../../lib/auth';
import { buildDecisionPlan, n8nDecideBodySchema } from '../../../../lib/n8n-super-agent';

function json200(body: Record<string, unknown>): Response {
  return Response.json(body, { status: 200 });
}

export async function POST(request: Request): Promise<Response> {
  const authError = requireAdminToken(request);
  if (authError) {
    return authError;
  }

  let raw: unknown;
  try {
    raw = await request.json();
  } catch {
    return json200({
      success: false,
      error: 'Invalid JSON body',
      observation: 'Request body must be valid JSON',
    });
  }

  const parsed = n8nDecideBodySchema.safeParse(raw);
  if (!parsed.success) {
    return json200({
      success: false,
      error: 'Invalid body',
      observation: parsed.error.message,
    });
  }

  const decision = buildDecisionPlan(parsed.data);
  return json200({
    success: true,
    observation: 'Decision generated by opsly_lili',
    ...decision,
  });
}
