import { extractIp, logAuditEvent } from '../../../../lib/audit';
import { requireAdminToken } from '../../../../lib/auth';
import { HTTP_STATUS } from '../../../../lib/constants';
import { buildDecisionPlan, n8nDecideBodySchema } from '../../../../lib/n8n-super-agent';
import { checkRateLimit } from '../../../../lib/rate-limiter';

function json200(body: Record<string, unknown>): Response {
  return Response.json(body, { status: 200 });
}

export async function POST(request: Request): Promise<Response> {
  const authError = requireAdminToken(request);
  if (authError) {
    return authError;
  }

  const ip = extractIp(request);
  const rateLimit = await checkRateLimit(ip ? `n8n-decide:${ip}` : 'n8n-decide:anonymous');
  if (!rateLimit.allowed) {
    return Response.json({ error: 'Too many requests' }, { status: HTTP_STATUS.TOO_MANY_REQUESTS });
  }

  let raw: unknown;
  try {
    raw = await request.json();
  } catch {
    return json200({
      success: false,
      error: 'Invalid JSON body',
      observation: 'Request body must be valid JSON',
    });
  }

  const parsed = n8nDecideBodySchema.safeParse(raw);
  if (!parsed.success) {
    return json200({
      success: false,
      error: 'Invalid body',
      observation: parsed.error.message,
    });
  }

  const decision = buildDecisionPlan(parsed.data);
  void logAuditEvent({
    action: 'n8n_decide',
    resource: 'n8n:decision',
    ip,
    user_agent: request.headers.get('user-agent') ?? undefined,
    metadata: {
      goal: parsed.data.goal,
    },
  });

  return json200({
    success: true,
    observation: 'Decision generated by opsly_lili',
    ...decision,
  });
}
