/**
 * Local flat config for `apps/admin`.
 *
 * CI runs `npx eslint .` inside this folder when it detects an ESLint config.
 * The repo root `eslint.config.mjs` intentionally ignores `apps/admin/**`,
 * so we provide a local flat config that adapts `.eslintrc.json` via FlatCompat.
 */
import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

const eslintrc = require("./.eslintrc.json");

export default [
  {
    ignores: [
      "eslint.config.mjs",
      // Generated by Next; we don't control its contents.
      "next-env.d.ts",
      ".next/**",
    ],
  },
  ...compat.config(eslintrc),
];

