import { ClassificationRule } from '../types';

export const DEFAULT_CLASSIFICATION_RULES: ClassificationRule[] = [
  // Credits exhausted
  {
    id: 'credits-exhausted-anthropic',
    name: 'Anthropic: Insufficient credits',
    pattern: /insufficient.*credits|credit.*limit|quota.*exceeded/i,
    category: 'credits_exhausted',
    strategy: 'operator_review',
    priority: 'critical',
    isRecoverable: true,
    suggestedAction: 'Review tenant billing and credit allocation',
    tags: ['billing', 'anthropic', 'critical'],
  },
  {
    id: 'credits-exhausted-stripe',
    name: 'Stripe: Payment failed',
    pattern: /payment.*failed|card.*declined|charge.*failed/i,
    category: 'credits_exhausted',
    strategy: 'operator_review',
    priority: 'critical',
    isRecoverable: true,
    suggestedAction: 'Notify tenant to update payment method',
    tags: ['billing', 'stripe', 'critical'],
  },

  // Rate limits
  {
    id: 'rate-limit-anthropic',
    name: 'Anthropic: Rate limit exceeded',
    pattern: /rate.*limit|too.*many.*requests|429/i,
    category: 'rate_limit',
    strategy: 'exponential_backoff',
    priority: 'high',
    maxRetries: 3,
    backoffMs: 2000,
    isRecoverable: true,
    suggestedAction: 'Automatic retry with exponential backoff',
    tags: ['rate_limit', 'anthropic', 'temporary'],
  },
  {
    id: 'rate-limit-redis',
    name: 'Redis: Rate limit',
    pattern: /WRONGTYPE|MOVED|CLUSTERDOWN/i,
    category: 'rate_limit',
    strategy: 'exponential_backoff',
    priority: 'high',
    maxRetries: 2,
    backoffMs: 1000,
    isRecoverable: true,
    suggestedAction: 'Automatic retry with backoff',
    tags: ['rate_limit', 'redis'],
  },

  // Timeouts
  {
    id: 'timeout-job',
    name: 'Job timeout',
    pattern: /timeout|exceeded.*time|timed.*out/i,
    category: 'timeout',
    strategy: 'auto_retry',
    priority: 'normal',
    maxRetries: 1,
    isRecoverable: true,
    suggestedAction: 'Increase timeout or optimize payload',
    tags: ['timeout', 'performance'],
  },
  {
    id: 'timeout-network',
    name: 'Network timeout',
    pattern: /ETIMEDOUT|EHOSTUNREACH|ENETUNREACH/i,
    category: 'timeout',
    strategy: 'exponential_backoff',
    priority: 'high',
    maxRetries: 2,
    isRecoverable: true,
    suggestedAction: 'Automatic retry with backoff',
    tags: ['timeout', 'network', 'temporary'],
  },

  // Configuration errors
  {
    id: 'config-error-credentials',
    name: 'Invalid credentials',
    pattern: /unauthorized|invalid.*key|authentication.*failed|403|401|invalid.*token/i,
    category: 'config_error',
    strategy: 'operator_review',
    priority: 'critical',
    isRecoverable: true,
    suggestedAction: 'Verify API keys and authentication configuration',
    tags: ['config', 'security', 'credentials'],
  },
  {
    id: 'config-error-missing-field',
    name: 'Missing required field',
    pattern: /required.*field|missing.*parameter|field.*required/i,
    category: 'config_error',
    strategy: 'fail_fast',
    priority: 'normal',
    isRecoverable: false,
    suggestedAction: 'Add missing required fields to job payload',
    tags: ['config', 'validation'],
  },
  {
    id: 'config-error-webhook',
    name: 'Invalid webhook URL',
    pattern: /invalid.*url|malformed.*webhook|404.*webhook/i,
    category: 'config_error',
    strategy: 'operator_review',
    priority: 'normal',
    isRecoverable: true,
    suggestedAction: 'Update webhook configuration',
    tags: ['config', 'webhook'],
  },

  // Provider errors (temporary)
  {
    id: 'provider-error-anthropic',
    name: 'Anthropic: Provider error',
    pattern: /error.*from.*anthropic|service.*unavailable|502|503|5\d\d/i,
    category: 'provider_error',
    strategy: 'exponential_backoff',
    priority: 'high',
    maxRetries: 3,
    backoffMs: 5000,
    isRecoverable: true,
    suggestedAction: 'Automatic retry; check Anthropic status page',
    tags: ['provider', 'anthropic', 'temporary'],
  },
  {
    id: 'provider-error-n8n',
    name: 'N8N: Workflow error',
    pattern: /n8n.*error|workflow.*failed|execution.*failed/i,
    category: 'provider_error',
    strategy: 'auto_retry',
    priority: 'high',
    maxRetries: 1,
    isRecoverable: true,
    suggestedAction: 'Review workflow configuration in N8N dashboard',
    tags: ['provider', 'n8n', 'workflow'],
  },
  {
    id: 'provider-error-google-drive',
    name: 'Google Drive: API error',
    pattern: /drive.*error|google.*api.*error|quota.*exceeded|forbidden/i,
    category: 'provider_error',
    strategy: 'exponential_backoff',
    priority: 'high',
    maxRetries: 2,
    isRecoverable: true,
    suggestedAction: 'Check Google Drive API quota and permissions',
    tags: ['provider', 'google-drive', 'api'],
  },

  // Irrecuperable errors
  {
    id: 'irrecuperable-assertion',
    name: 'Assertion failed',
    pattern: /assertion.*failed|assert.*error/i,
    category: 'irrecuperable',
    strategy: 'fail_fast',
    priority: 'critical',
    isRecoverable: false,
    suggestedAction: 'Fix code assertion; contact engineering',
    tags: ['fatal', 'code-error'],
  },
  {
    id: 'irrecuperable-type-error',
    name: 'Type error in execution',
    pattern: /cannot.*read.*property|undefined.*not.*object|type.*error/i,
    category: 'irrecuperable',
    strategy: 'fail_fast',
    priority: 'critical',
    isRecoverable: false,
    suggestedAction: 'Fix type error in code; add proper validation',
    tags: ['fatal', 'code-error', 'type-safety'],
  },
  {
    id: 'irrecuperable-parse-error',
    name: 'JSON parse error',
    pattern: /json.*parse.*error|unexpected.*token|invalid.*json/i,
    category: 'irrecuperable',
    strategy: 'fail_fast',
    priority: 'high',
    isRecoverable: false,
    suggestedAction: 'Validate JSON payload structure',
    tags: ['fatal', 'data-error', 'format'],
  },
];
