import type { RelationshipEdge } from '../types.js';

export const CANONICAL_RELATIONSHIPS: RelationshipEdge[] = [
  {
    id: 'traveler-mentor-nova',
    from: 'traveler',
    to: 'nova',
    kind: 'mentor',
    description: 'Traveler mentors NØVA without finishing NØVA’s identity.',
  },
  {
    id: 'traveler-protector-kai',
    from: 'traveler',
    to: 'kai',
    kind: 'protector',
    description: 'Traveler protects Kai’s right to keep asking.',
  },
  {
    id: 'nova-sibling-kai',
    from: 'nova',
    to: 'kai',
    kind: 'older-brother-energy',
    description: 'NØVA offers older-sibling spark: try, then care.',
  },
  {
    id: 'lyra-science-mentor-nova',
    from: 'lyra',
    to: 'nova',
    kind: 'science-mentor',
    description: 'Lyra teaches method so NØVA’s impulse can survive evidence.',
  },
  {
    id: 'orion-sports-mentor-kai',
    from: 'orion',
    to: 'kai',
    kind: 'sports-mentor',
    description: 'Orion coaches Kai’s body without shutting down Kai’s questions.',
  },
  {
    id: 'atlas-builder-companion-traveler',
    from: 'atlas',
    to: 'traveler',
    kind: 'builder-companion',
    description: 'Atlas walks builder and rescue paths beside Traveler.',
  },
  {
    id: 'maya-nature-guide-group',
    from: 'maya',
    to: 'group',
    kind: 'nature-guide',
    description: 'Maya guides the group through living systems and labeled stories.',
  },
  {
    id: 'echo-intelligence-everyone',
    from: 'echo',
    to: 'everyone',
    kind: 'intelligence-companion',
    description: 'Echo helps everyone search and remember, without becoming an oracle.',
  },
  {
    id: 'wavo-play-kai',
    from: 'wavo',
    to: 'kai',
    kind: 'play-companion',
    description: 'Wavo plays in water with Kai and yields technique to Orion.',
  },
  {
    id: 'wavo-defers-orion',
    from: 'wavo',
    to: 'orion',
    kind: 'defers-to',
    description: 'Wavo is not the swimming teacher of record.',
  },
  {
    id: 'arena-brissa-sisters',
    from: 'arena',
    to: 'brissa',
    kind: 'sisters',
    description: 'Arena and Brissa are sisters and the emotional center of Astral Arena.',
  },
  {
    id: 'brissa-orion-shepherd-companion',
    from: 'brissa',
    to: 'orion-shepherd',
    kind: 'chosen-companions',
    description: 'Brissa and Orion protect and navigate together; Orion remains a nonverbal German Shepherd guardian.',
  },
  {
    id: 'arena-aurora-companion',
    from: 'arena',
    to: 'aurora-unicorn',
    kind: 'chosen-companions',
    description: 'Arena and Aurora choose to travel together; Aurora is never owned or treated as property.',
  },
  {
    id: 'brissa-asterion-alliance',
    from: 'brissa',
    to: 'asterion',
    kind: 'dragon-alliance',
    description: 'Asterion chooses Brissa after she restores a lost constellation rather than trying to command him.',
  },
  {
    id: 'arena-pyra-alliance',
    from: 'arena',
    to: 'pyra',
    kind: 'dragon-alliance',
    description: 'Pyra chooses Arena after Arena recognizes fear inside the crystal instead of treating the dragon as a monster.',
  },
  {
    id: 'nx7-nebryx-sync',
    from: 'nx-7',
    to: 'nebryx',
    kind: 'living-technology-alliance',
    description: 'Nebryx lets NX-7 experience a living Nexus Current, bridging constructed and grown intelligence.',
  },
  {
    id: 'umbra-umbriel-memory-bond',
    from: 'umbra',
    to: 'umbriel',
    kind: 'ancient-guardian-bond',
    description: 'Umbriel was Umbra’s dragon ally before the fall and preserves one memory-thread of the Guardian he used to be.',
  },
  {
    id: 'altair-umbra-old-allies',
    from: 'altair',
    to: 'umbra',
    kind: 'former-allies',
    description: 'Altair knew Umbra before he became Señor Sombra and carries guilt for failing to stop the fall.',
  },
  {
    id: 'altair-brissa-mentor',
    from: 'altair',
    to: 'brissa',
    kind: 'mentor',
    description: 'Altair teaches Brissa the Language of the Currents but must learn not to make her choices for her.',
  },
  {
    id: 'altair-arena-mentor',
    from: 'altair',
    to: 'arena',
    kind: 'mentor',
    description: 'Altair offers history and safe boundaries while Arena’s imagination finds solutions his generation missed.',
  },
];
