#!/bin/bash
#
# Runtime Setup Wizard
# Week 2: Setup automatizado para entorno local
# Usage: ./scripts/runtime-setup-wizard.sh [--dry-run] [--os=macos|linux|windows]
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
DRY_RUN=false
TARGET_OS=""
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Logging functions
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Usage
usage() {
  cat << EOF
Usage: $0 [OPTIONS]

Setup wizard for Local-First Runtime Environment

OPTIONS:
  --dry-run       Show what would be done without doing it
  --os OS         Target OS: macos, linux, windows (auto-detected by default)
  -h, --help      Show this help

EXAMPLES:
  $0                    # Auto-detect OS and setup
  $0 --dry-run          # Preview changes
  $0 --os=linux         # Force Linux setup

EOF
  exit 0
}

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run) DRY_RUN=true; shift ;;
    --os) TARGET_OS="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) log_error "Unknown option: $1"; exit 1 ;;
  esac
done

# Detect OS
detect_os() {
  if [[ -n "$TARGET_OS" ]]; then
    echo "$TARGET_OS"
    return
  fi

  case "$(uname -s)" in
    Darwin*) echo "macos" ;;
    Linux*) echo "linux" ;;
    MINGW*|MSYS*|CYGWIN*) echo "windows" ;;
    *) echo "unknown" ;;
  esac
}

# Check if command exists
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# Setup for macOS
setup_macos() {
  log_info "Setting up macOS environment..."

  local packages=("node" "python3" "docker")

  # Check Homebrew
  if ! command_exists brew; then
    log_warn "Homebrew not found. Install from: https://brew.sh"
    return 1
  fi

  for pkg in "${packages[@]}"; do
    if command_exists "$pkg"; then
      log_success "$pkg already installed"
    else
      if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would install: $pkg"
      else
        log_info "Installing $pkg..."
        # brew install "$pkg" || log_warn "Failed to install $pkg"
      fi
    fi
  done

  # Check for Cursor
  if [[ -d "/Applications/Cursor.app" ]]; then
    log_success "Cursor found"
  else
    log_warn "Cursor not found. Install from: https://cursor.sh"
  fi

  # Setup Ollama
  if command_exists ollama; then
    log_success "Ollama installed"
    if [[ "$DRY_RUN" != "true" ]]; then
      # ollama serve &
      log_info "Ollama is available"
    fi
  else
    log_warn "Ollama not found. Install with: brew install ollama"
  fi
}

# Setup for Linux
setup_linux() {
  log_info "Setting up Linux environment..."

  # Check package manager
  local pkg_manager=""
  if command_exists apt-get; then
    pkg_manager="apt"
  elif command_exists yum; then
    pkg_manager="yum"
  elif command_exists dnf; then
    pkg_manager="dnf"
  fi

  if [[ -z "$pkg_manager" ]]; then
    log_error "No supported package manager found"
    return 1
  fi

  local packages=("nodejs" "npm" "python3" "docker.io")

  for pkg in "${packages[@]}"; do
    if command_exists "$pkg"; then
      log_success "$pkg already installed"
    else
      if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would install: $pkg"
      else
        log_info "Installing $pkg..."
        # sudo "$pkg_manager" install -y "$pkg" || log_warn "Failed to install $pkg"
      fi
    fi
  done

  # Setup Ollama
  if command_exists ollama; then
    log_success "Ollama installed"
  else
    log_warn "Ollama not found. Install with: curl -fsSL https://ollama.com/install.sh | sh"
  fi
}

# Setup for Windows (WSL)
setup_windows() {
  log_info "Setting up Windows (WSL) environment..."

  # Check if running in WSL
  if [[ -f /proc/version ]] && grep -qi microsoft /proc/version; then
    log_info "Detected WSL"
    setup_linux
  else
    log_warn "WSL not detected. This script should run inside WSL."
    log_info "Run: wsl --install -d Ubuntu"
  fi
}

# Create config file
create_config() {
  local config_file="$PROJECT_ROOT/.env.local"

  if [[ -f "$config_file" ]]; then
    log_warn "Config file already exists: $config_file"
    return 0
  fi

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "[DRY-RUN] Would create: $config_file"
    return 0
  fi

  cat > "$config_file" << 'EOF'
# Local-First Runtime Configuration
# Generated by runtime-setup-wizard.sh

# Enable local execution
OPSLY_LOCAL_AGENTS_ENABLED=true

# Ollama settings
OPSLY_LOCAL_OLLAMA_URL=http://localhost:11434
OPSLY_LOCAL_OLLAMA_MODEL=llama3.2

# Preferred agent (auto-selected by default)
# Options: cursor, claude, codex, opencode, ollama, remote
OPSLY_LOCAL_PREFERRED_AGENT=auto

# Timeouts (ms)
OPSLY_LOCAL_TIMEOUT_MS=30000
OPSLY_LOCAL_MAX_RETRIES=3
EOF

  log_success "Created config: $config_file"
}

# Verify environment
verify_environment() {
  log_info "Verifying environment..."

  # Check Node.js
  if command_exists node; then
    log_success "Node.js: $(node --version)"
  else
    log_warn "Node.js not found"
  fi

  # Check npm
  if command_exists npm; then
    log_success "npm: $(npm --version)"
  else
    log_warn "npm not found"
  fi

  # Check Docker
  if command_exists docker; then
    if docker info >/dev/null 2>&1; then
      log_success "Docker: running"
    else
      log_warn "Docker installed but not running"
    fi
  else
    log_warn "Docker not found"
  fi

  # Check Ollama
  if command_exists ollama; then
    log_success "Ollama: available"
    if curl -s http://localhost:11434/api/tags >/dev/null 2>&1; then
      log_success "Ollama: running"
    else
      log_warn "Ollama not running (run: ollama serve)"
    fi
  else
    log_warn "Ollama not found"
  fi
}

# Main
main() {
  log_info "=== Local-First Runtime Setup Wizard ==="

  local os=$(detect_os)
  log_info "Detected OS: $os"

  if [[ "$os" == "unknown" ]]; then
    log_error "Could not detect OS. Use --os to specify."
    exit 1
  fi

  case "$os" in
    macos) setup_macos ;;
    linux) setup_linux ;;
    windows) setup_windows ;;
    *) log_error "Unsupported OS: $os"; exit 1 ;;
  esac

  create_config
  verify_environment

  log_success "=== Setup Complete ==="
  log_info "Next steps:"
  log_info "  1. Review .env.local configuration"
  log_info "  2. Run: npm run type-check"
  log_info "  3. Test: ./scripts/runtime-health-check.sh"
}

main "$@"