import type { UniverseWorld } from '../types.js';

const ASTRAL_ARENA_CAST = [
  'arena',
  'brissa',
  'orion-shepherd',
  'aurora-unicorn',
  'nx-7',
  'altair',
  'umbra',
  'asterion',
  'pyra',
  'nebryx',
  'umbriel',
];

const ALL = [
  'traveler',
  'nova',
  'kai',
  'lyra',
  'orion',
  'atlas',
  'maya',
  'echo',
  'wavo',
];

export const CANONICAL_WORLDS: UniverseWorld[] = [
  {
    id: 'technolia',
    slug: 'technolia',
    name: 'TECHNOLIA',
    description:
      'A buildable technology civilization connected to Astral Arena. Guardians gather resources, research software architecture, construct machines, defend safe cyber ranges, assemble a starship, and progressively reveal the stellar map.',
    visualIdentity: {
      palette: ['deep navy', 'electric blue', 'royal purple', 'antique gold', 'crystal cyan'],
      architecture:
        'Modular Nexus settlements, gateway towers, observatories, queues as luminous docks, worker foundries, data vaults, starship yards, and distributed stellar outposts',
      atmosphere: 'Constructive strategy, discovery, engineering, defense, and visible progression',
      lighting: 'Clean technological glow with warm gold guidance lights; readable systems over neon clutter',
      motifs: ['network graphs', 'crystal circuits', 'modular buildings', 'star maps', 'Nexus rings', 'dragon-current routes'],
      negatives: [
        'real-world exploit instructions',
        'military realism as the core fantasy',
        'grimdark cyberpunk',
        'opaque technology with no learning purpose',
      ],
    },
    themes: ['building', 'systems thinking', 'security', 'resilience', 'exploration', 'cooperation'],
    allowedCharacters: ASTRAL_ARENA_CAST,
    educationalDomains: [
      'software architecture',
      'distributed systems',
      'cybersecurity defense',
      'observability',
      'platform engineering',
      'resource planning',
    ],
    transitions: ['astral-arena', 'nexus', 'future', 'lab', 'unknown'],
    portalSymbol: 'crystal circuit inside a starship ring',
  },
  {
    id: 'astral-arena',
    slug: 'astral-arena',
    name: 'ASTRAL ARENA',
    description:
      'A family fantasy-sci-fi realm inside the wider Nexus: Crystal Temple, Celestial City, the Forest Without Sky, Dragon Sanctuaries, living Nexus Currents, and the Great Rift. Arena and Brissa are its central sister-heroes.',
    visualIdentity: {
      palette: ['night navy', 'royal purple', 'deep blue', 'rose pink', 'antique gold', 'star white'],
      architecture:
        'Floating crystal temples, luminous bridges, constellation cities, dragon sanctuaries, ring portals, and ancient technology grown into living geometry',
      atmosphere: 'Wonder, movement, family warmth, cosmic danger without horror',
      lighting: 'Cinematic starlight, purple-blue volumetric glow, warm gold faces, restrained pink energy accents',
      motifs: ['woven star threads', 'constellation shields', 'winged Nexus rings', 'dragon currents', 'crystal gates'],
      negatives: [
        'gore',
        'horror-child imagery',
        'hypersexualized child heroes',
        'religious iconography presented as theology',
        'trademarked superhero costume imitation',
        'generic neon cyberpunk overload',
      ],
    },
    themes: ['sisterhood', 'repair', 'memory', 'courage', 'cooperation', 'second chances'],
    allowedCharacters: ASTRAL_ARENA_CAST,
    educationalDomains: [
      'astronomy-lite clearly separated from fantasy',
      'maps and systems',
      'technology responsibility',
      'teamwork and emotional learning',
      'fictional creature ecology clearly labeled as fiction',
    ],
    transitions: ['nexus', 'unknown', 'technolia'],
    portalSymbol: 'woven star inside an open Nexus ring',
  },
  {
    id: 'nexus',
    slug: 'nexus',
    name: 'NEXUS',
    description: 'The crossroads. Portals, memory, and unfinished maps. Home frequency of Echo.',
    visualIdentity: {
      palette: ['night navy', 'electric blue', 'antique gold'],
      architecture: 'Ringed thresholds, floating paths, geometry that feels ancient and built',
      atmosphere: 'Quiet awe, navigable mystery',
      lighting: 'Volumetric portal light, restrained gold',
      motifs: ['rings', 'constellations', 'incomplete maps'],
      negatives: ['cyberpunk clutter', 'hellish red', 'Marvel cosmic explosion'],
    },
    themes: ['connection', 'memory', 'thresholds', 'unfinished knowledge'],
    allowedCharacters: ALL,
    educationalDomains: ['systems', 'information', 'identity', 'maps'],
    transitions: ['earth', 'mind', 'future', 'wild', 'move', 'lab', 'origins', 'unknown'],
    portalSymbol: 'open double ring',
  },
  {
    id: 'earth',
    slug: 'earth',
    name: 'EARTH',
    description: 'Lived-in human world: cities, kitchens, schools, coasts. Where questions start ordinary.',
    visualIdentity: {
      palette: ['daylight', 'concrete-warm', 'plant green'],
      architecture: 'Recognizable human places, slightly heightened',
      atmosphere: 'Familiar, ready to tilt into wonder',
      lighting: 'Natural daylight, practical interiors',
      motifs: ['doors', 'windows', 'tools on tables'],
      negatives: ['generic stock-city', 'dystopia-as-default'],
    },
    themes: ['everyday', 'community', 'craft', 'home'],
    allowedCharacters: ALL,
    educationalDomains: ['daily life', 'civics-lite', 'home science'],
    transitions: ['nexus', 'wild', 'move', 'lab'],
    portalSymbol: 'circle in a doorway',
  },
  {
    id: 'mind',
    slug: 'mind',
    name: 'MIND',
    description: 'Inner space: ideas, attention, feelings as visitable rooms. Not a diagnosis simulator.',
    visualIdentity: {
      palette: ['soft violet', 'paper white', 'thought-blue'],
      architecture: 'Abstract rooms, libraries of attention, gentle surrealism',
      atmosphere: 'Introspective, safe, never horror-psyche',
      lighting: 'Diffuse, kind',
      motifs: ['threads of thought', 'doors of attention'],
      negatives: ['nightmare imagery', 'clinical coldness as cruelty'],
    },
    themes: ['attention', 'learning', 'feelings', 'identity'],
    allowedCharacters: ['nova', 'kai', 'echo', 'traveler', 'lyra'],
    educationalDomains: ['learning how to learn', 'emotions', 'focus'],
    transitions: ['nexus', 'earth'],
    portalSymbol: 'spiral of attention (metaphor, not occult science)',
  },
  {
    id: 'future',
    slug: 'future',
    name: 'FUTURE',
    description: 'Possible tomorrows as workshops, not prophecy. Atlas and NØVA belong here as builders.',
    visualIdentity: {
      palette: ['clean silver', 'soft gold', 'sky cyan'],
      architecture: 'Prototypes, scaffolds, unfinished cities that still have trees',
      atmosphere: 'Hopeful work-in-progress',
      lighting: 'Bright, honest, fewer neon nights',
      motifs: ['scaffolds', 'prototypes', 'green infrastructure'],
      negatives: ['cyberpunk grimdark', 'tech-bro utopia without people'],
    },
    themes: ['building', 'responsibility', 'infrastructure', 'hope with labor'],
    allowedCharacters: ['traveler', 'nova', 'atlas', 'echo', 'lyra', 'kai'],
    educationalDomains: ['engineering', 'technology ethics', 'design'],
    transitions: ['nexus', 'earth', 'lab'],
    portalSymbol: 'scaffold ring',
  },
  {
    id: 'wild',
    slug: 'wild',
    name: 'WILD',
    description: 'Living systems. Maya’s primary path. Animals are subjects, not props.',
    visualIdentity: {
      palette: ['canopy green', 'soil', 'river teal'],
      architecture: 'Little architecture; trails, roots, water',
      atmosphere: 'Alive, specific, not generic jungle stock',
      lighting: 'Dappled, golden hour, weather that means something',
      motifs: ['tracks', 'pollination', 'canopy layers'],
      negatives: ['safari trophy', 'monster forest', 'sacred-geometry overlay as physics'],
    },
    themes: ['ecosystems', 'animals', 'conservation', 'attention to small life'],
    allowedCharacters: ['maya', 'kai', 'lyra', 'traveler', 'echo', 'nova'],
    educationalDomains: ['ecology', 'biology', 'conservation'],
    transitions: ['nexus', 'earth', 'origins'],
    portalSymbol: 'seed inside a ring',
  },
  {
    id: 'move',
    slug: 'move',
    name: 'MOVE',
    description: 'Bodies in practice: water, sport, teamwork. Orion’s house. Peskids swimming lives here.',
    visualIdentity: {
      palette: ['pool blue', 'lane white', 'sun'],
      architecture: 'Pools, courts, coasts, huddle spaces',
      atmosphere: 'Energetic, safe, coached',
      lighting: 'Caustics, sport daylight',
      motifs: ['lanes', 'breath', 'team circles'],
      negatives: ['gladiator arena', 'injury spectacle'],
    },
    themes: ['sport', 'discipline', 'water', 'team'],
    allowedCharacters: ['orion', 'kai', 'wavo', 'nova', 'traveler', 'echo'],
    educationalDomains: ['physical education', 'water safety', 'teamwork'],
    transitions: ['nexus', 'earth'],
    portalSymbol: 'wave through a ring',
  },
  {
    id: 'lab',
    slug: 'lab',
    name: 'LAB',
    description: 'Method. Instruments. How we know. Lyra’s house.',
    visualIdentity: {
      palette: ['ivory', 'sage', 'instrument copper'],
      architecture: 'Benches, field tables, clean without being inhuman',
      atmosphere: 'Focus, permission to be wrong then check',
      lighting: 'Practical, daylight, stars as data when astronomy',
      motifs: ['lenses', 'notes', 'comparisons'],
      negatives: ['mad-scientist chaos', 'magic runes as UI'],
    },
    themes: ['method', 'evidence', 'biology', 'astronomy', 'medicine-lite'],
    allowedCharacters: ['lyra', 'nova', 'echo', 'kai', 'traveler', 'maya'],
    educationalDomains: ['scientific method', 'life science', 'space science'],
    transitions: ['nexus', 'earth', 'future', 'origins'],
    portalSymbol: 'lens-ring',
  },
  {
    id: 'origins',
    slug: 'origins',
    name: 'ORIGINS',
    description: 'Beginnings: cultural memory, deep time, origin stories. Fiction must be labeled when teaching.',
    visualIdentity: {
      palette: ['clay', 'night sky', 'bone-white'],
      architecture: 'Thresholds, hearths, stone that remembers hands',
      atmosphere: 'Respectful, not theme-park ancient',
      lighting: 'Firelight and stars, never occult-power FX as science',
      motifs: ['hearth', 'oral maps', 'deep-time layers'],
      negatives: ['colonial treasure hunt', 'ancient-aliens as fact', 'sacred geometry physics'],
    },
    themes: ['memory', 'story', 'deep time', 'respect'],
    allowedCharacters: ['maya', 'lyra', 'traveler', 'kai', 'echo', 'nova'],
    educationalDomains: ['history-as-story', 'anthropology-lite', 'earth deep time as science when evidenced'],
    transitions: ['nexus', 'wild', 'lab'],
    portalSymbol: 'hearth-ring',
  },
  {
    id: 'unknown',
    slug: 'unknown',
    name: 'UNKNOWN',
    description: 'The unfinished map. Wonder without fake answers. Traveler is comfortable here.',
    visualIdentity: {
      palette: ['fog blue', 'gold fragment', 'unlit navy'],
      architecture: 'Incomplete paths, half-drawn geometry',
      atmosphere: 'Honest not-knowing',
      lighting: 'Sparse, a lantern, a fragment of gold',
      motifs: ['blank map', 'question marks as invitation'],
      negatives: ['jump-scare unknown', 'conspiracy chalkboard'],
    },
    themes: ['uncertainty', 'exploration', 'humility'],
    allowedCharacters: ['traveler', 'echo', 'nova', 'kai', 'lyra'],
    educationalDomains: ['scientific humility', 'exploration'],
    transitions: ['nexus', 'mind', 'future'],
    portalSymbol: 'broken ring',
  },
];
